### PR TITLE
Fix OSGi package export version

### PR DESCRIPTION
**Pull request by stefanseifert**
OSGi version from package-info got ignored, updating them with each new bundle release
add "impl" to all internal package, and remove explicit bundle export package instruction from pom

### CODE REVIEW

**Comment by JEBailey** [comment]
@trekawek and @npeltier could you look at this? I believe you both would be better judges of impact then I am.

**Comment by trekawek** [comment]
@stefanseifert - thanks for looking into this!

I understand that the manual exports are redundant, as the bundle plugin is able to export all the packages with `package-info.java` automatically. Manual export also breaks the package versioning, right?

Could you explain why it's also required to move the other classes into the `impl` package? Is it treated in some special way as well?

**Comment by stefanseifert** [comment]
the way it was before the PR the version from the package-info files got ignored, because of the explicit declaration of the maven bundle plugin:
```
<configuration>
  <instructions>
    <Export-Package>!*,org.apache.sling.query,org.apache.sling.query.api</Export-Package>
  </instructions>
</configuration>
```

if we want to keep this notation we would need to add the package version to the export package statement here. but using package-info files is far more intuitive and used in most of the other sling modules. so it thought it's good to keep the practise if hiding the private package by the convention of adding "impl" or "internal" to the package name and let the maven bundle plugin do the rest (which is the usual pattern in the other sling modules - at least when they are not converted to the bnd-maven-plugin).

anyway for a developer it's also helpful to see clearly from the package name if it's private or public class.

**Comment by trekawek** [comment]
OK, so the `impl` package is treated in a special way. Cool, thanks for this!

**Pull request merged**
